server:
  port: 8002
spring:
  common:
  labtrac-qlms:
    url: jdbc:xxxxx://devsql.xxxxxx.us-east-1.rds.amazonaws.com:3306/xxxxxx?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=EST5EDT
    username: xxxxxxx
    password: xxxxxxx
