server:
  port: 8002
spring:
  common:
  labtrac-qlms:
    url: jdbc:mysql://##################.rds.amazonaws.com:3306/labtrac-qlms?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=EST5EDT
    username: #############
    password: #############
